CRITICAL - 2022-05-14 13:54:04 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:55:08 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:55:09 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:55:39 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:56:02 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:56:03 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:56:03 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:56:04 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-05-14 13:56:08 --> Class "App\Controllers\Model_User" not found
#0 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(809): App\Controllers\Auth->__construct()
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-05-14 14:08:59 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:08:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:09:18 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:09:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:09:29 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:09:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:09:33 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:09:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:09:38 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:09:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:10:45 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:10:45 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:10:59 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:10:59 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:21 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:23 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:23 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:25 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:28 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:49 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:11:57 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:11:57 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:12:28 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:12:28 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:12:38 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:12:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:13:04 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:13:04 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:13:12 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:13:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:13:15 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:13:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('asd', 'user_password', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('password', 'password', 'asd', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(61): CodeIgniter\Controller->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#8 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2022-05-14 14:14:05 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:14:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('user_username', 'user_username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(1347): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#6 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(707): CodeIgniter\BaseModel->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): CodeIgniter\BaseModel->save(Array)
#10 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#11 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-05-14 14:16:30 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:16:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('user_username', 'user_username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(1347): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#6 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(707): CodeIgniter\BaseModel->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): CodeIgniter\BaseModel->save(Array)
#10 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#11 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-05-14 14:16:31 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:16:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('user_username', 'user_username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(1347): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#6 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(707): CodeIgniter\BaseModel->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): CodeIgniter\BaseModel->save(Array)
#10 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#11 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2022-05-14 14:17:12 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2022-05-14 14:17:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 F:\XAMPP\htdocs\trashedu\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 F:\XAMPP\htdocs\trashedu\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 F:\XAMPP\htdocs\trashedu\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#3 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('a', 'user_username', Array, NULL)
#4 F:\XAMPP\htdocs\trashedu\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('user_username', 'user_username', 'a', Array, Array)
#5 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(1347): CodeIgniter\Validation\Validation->run(Array, NULL, NULL)
#6 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(707): CodeIgniter\BaseModel->validate(Array)
#7 F:\XAMPP\htdocs\trashedu\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#8 F:\XAMPP\htdocs\trashedu\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#9 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): CodeIgniter\BaseModel->save(Array)
#10 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#11 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2022-05-14 14:24:34 --> password_hash() expects at least 2 arguments, 1 given
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): password_hash('asdb')
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:24:55 --> password_hash() expects at least 2 arguments, 1 given
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(75): password_hash('asdb')
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Register()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:41:33 --> Undefined property: App\Controllers\Auth::$model_User
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(120): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'F:\\XAMPP\\htdocs...', 120)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:41:54 --> Undefined property: App\Controllers\Auth::$model_User
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(120): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'F:\\XAMPP\\htdocs...', 120)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:42:08 --> Undefined property: App\Controllers\Auth::$model_User
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(120): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'F:\\XAMPP\\htdocs...', 120)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:42:13 --> Undefined variable $data_full
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(134): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'F:\\XAMPP\\htdocs...', 134)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:42:20 --> Undefined variable $data_full
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(134): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'F:\\XAMPP\\htdocs...', 134)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-14 14:42:24 --> Undefined variable $data_full
#0 F:\XAMPP\htdocs\trashedu\app\Controllers\Auth.php(134): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'F:\\XAMPP\\htdocs...', 134)
#1 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(832): App\Controllers\Auth->Login()
#2 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 F:\XAMPP\htdocs\trashedu\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 F:\XAMPP\htdocs\trashedu\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
